name: Lint

on:
  push:
    branches: [main]
    paths:
      - grammar.js
      - main/**
  pull_request:
    paths:
      - grammar.js
      - main/**

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Check formatting
        run: deno fmt --check main/

      - name: Run linter
        run: deno lint main/
